### ISSUE TITLE
Retire in favour of pybufrkit?

### ISSUE THREAD

**Issue by gerritholl** [pytroll/trollbufr#33]
The trollbufr package appears poorly maintained.  It has a single failing unit test (see #25 dating from February 2019) with 34% test coverage and no PRs have been merged since over two years.  A different package, [pybufrkit](https://github.com/ywangd/pybufrkit), appears to have the same aims, a pure Python bufr reader.  It has 45 passing unit tests with 82% test coverage.  It is [publicly recommended by DWD](https://www.dwd.de/EN/aboutus/it/functions/Teasergroup/bufr.html) and sees some maintenance (last version released less than three months ago, 12 May 2021).

Is there some unique functionality in trollbufr that is missing in pybufrkit, or another reason to continue maintaining both packages?

**Comment by alexmaul** [comment]
Trollbufr has indeed a lack of unit tests. 
There won't be many / regular updates, since I deem it complete enough to handle all data currently flowing through GTS.
I'm still open to new developments regarding BUFR and would implement them.

BTW pybufrkit has regular updates because the BUFR tables have to be converted to a pybufrkit-specific format. Trollbufr is using the tables in formats provided by ECMWF and DWD.
